### ISSUE TITLE
Rewrite "make_routes" in JavaScript

### ISSUE THREAD

**Issue by jcbwlkr** [openwichita/busICT#3]
We have [this file](https://github.com/openwichita/busICT/blob/master/lib/make_routes.php) which is responsible for taking the GEOJSON dump from the city and translating it into the format we need. During the hackathon I just slapped that script together in PHP because it was easy. I don't mind it myself, but it does add an extra dependency for maintenance. Rewrite that script with the equivalent JavaScript that can be executed with something like `node make_routes.js` or something.

**Comment by hitjim** [comment]
Giving this one a look

**Comment by hitjim** [comment]
See.  I thought the way I worded my PR this would get closed.  Closing.
