### ISSUE TITLE
Add bus stops to routes

### ISSUE THREAD

**Issue by jcbwlkr** [openwichita/busICT#4]
The city has provided information on bus stops at http://portal.wichitagis.opendata.arcgis.com/datasets/1c9780e257fe4bb18df70bd4a30379ff_0

These should be shown on the map as well. I would take an approach similar to the `lib/routes.js` which is generated by `lib/make_routes.php` (also see #3).

If stops are tied to routes then I would also like to see the stops hide/show then you hide/show a route. If they aren't tied to routes in the data then probably just show them.

Also if you want to find an open source icon or create one that represents a bus stop you can use that for the marker instead of a generic shape.

**Comment by mjvandecreek** [comment]
curl -O http://portal.wichitagis.opendata.arcgis.com/datasets/1c9780e257fe4bb18df70bd4a30379ff_0.geojson

looks like the mapping between routes and stops is:
routes -> "name":"COLLEGE HILL"
stops -> "BUSROUTE": "College Hill"

**Comment by Mearnest** [comment]
We got this working at labor party locally. It has been pushed to my fork. The make_bus_stops.js file is in the .datasrc directory inside lib to hide it from meteor. Navigate to the .datasrc folder, and run "node make_bus_stops.js". It will attempt to fetch the bus stop geojson data from the portal. If there is an error, it will read the existing local file which we curled into.

**Comment by Mearnest** [comment]
ToDo: match the bus stops to the route they belong, so they can be turned on and off with the routes in the interface.

**Comment by Mearnest** [comment]
Made second commit so that naming scheme is consistent with variables and files. Was using "bus_stops" instead of just "stops". Would have deleted fork and started another, but didn't know how to do that.

**Comment by Mearnest** [comment]
Unfortunately, not all the routes differ by just uppercase. 
routes -> "name": "E CENTRAL"
stops -> "BUSROUTE": "East Central"
This seems to be the case for all directional routes.

**Comment by jcbwlkr** [comment]
@Mearnest it gets worse. The vehicle locations resource uses yet another set of route ids/names to associate vehicles with a route.

Let's go ahead and get the stops added without associating them with a route. I think we can come up with some better all-encompassing route identifying solution.

**Comment by Mearnest** [comment]
Okay, I'll push to my new fork with just the stops added.

**Comment by Mearnest** [comment]
I have come across an intermittent error when clicking on and off layers. It complains about the layer not existing, but I can't consistently reproduce it, so I'm not sure what combination of clicks causes it. It doesn't seem to break anything in the interface, though.
